import { useState } from "react";
import { requestPermission } from "../notifications";

function exportToCSV(expenses) {
  const headers = ["Date","Type","Category","Label","Amount"];
  const rows = expenses.map(e => [e.date, e.type, e.category, `"${e.label}"`, e.amount]);
  const csv  = [headers,...rows].map(r => r.join(",")).join("\n");
  const blob = new Blob([csv], { type:"text/csv" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = `rupeetrack-${new Date().toISOString().slice(0,7)}.csv`; a.click();
  URL.revokeObjectURL(url);
}

function exportToJSON(expenses) {
  const blob = new Blob([JSON.stringify(expenses,null,2)], { type:"application/json" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = `rupeetrack-${new Date().toISOString().slice(0,7)}.json`; a.click();
  URL.revokeObjectURL(url);
}

function generateTextReport(expenses, budget) {
  const expenseOnly = expenses.filter(e => e.type==="expense");
  const income      = expenses.filter(e => e.type==="income").reduce((s,e)=>s+e.amount,0);
  const totalSpent  = expenseOnly.reduce((s,e)=>s+e.amount,0);
  const savings     = income - totalSpent;
  const catMap = {};
  expenseOnly.forEach(e => { catMap[e.category]=(catMap[e.category]||0)+e.amount; });
  const catBreakdown = Object.entries(catMap).sort((a,b)=>b[1]-a[1]).map(([cat,amt]) => `  ${cat.padEnd(16)} ₹${amt.toLocaleString("en-IN")}`).join("\n");
  const report = `
========================================
       RUPEETRACK — MONTHLY REPORT
       ${new Date().toLocaleDateString("en-IN",{month:"long",year:"numeric"})}
========================================

SUMMARY
-------
Total Income   : ₹${income.toLocaleString("en-IN")}
Total Spent    : ₹${totalSpent.toLocaleString("en-IN")}
Monthly Budget : ₹${budget.toLocaleString("en-IN")}
Remaining      : ₹${(budget-totalSpent).toLocaleString("en-IN")}
Total Savings  : ₹${savings.toLocaleString("en-IN")}
Savings Rate   : ${income>0?Math.round((savings/income)*100):0}%

SPENDING BY CATEGORY
--------------------
${catBreakdown}

RECENT TRANSACTIONS (Last 10)
------------------------------
${expenses.slice(0,10).map(e=>`  ${e.date}  ${e.type==="income"?"+":"-"}₹${String(e.amount).padStart(8)}  ${e.label}`).join("\n")}

========================================
Generated by RupeeTrack on ${new Date().toLocaleDateString("en-IN")}
========================================`.trim();
  const blob = new Blob([report],{type:"text/plain"});
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href=url; a.download=`rupeetrack-report-${new Date().toISOString().slice(0,7)}.txt`; a.click();
  URL.revokeObjectURL(url);
}

export default function Profile({ user, budget, setBudget, onNavigate, onLogout }) {
  const [editingBudget, setEditingBudget] = useState(false);
  const [budgetInput,   setBudgetInput]   = useState(String(budget));
  const [notifications, setNotifications] = useState(true);
  const [exportDone,    setExportDone]    = useState("");

  const getExpenses = () => { try { return JSON.parse(localStorage.getItem("rt_expenses")||"[]"); } catch { return []; } };
const clearData = () => {
  const confirmed = window.confirm(
    "Are you sure you want to delete all expense data?"
  );

  if (!confirmed) return;

  localStorage.removeItem("rt_expenses");
  alert("Data deleted successfully!");

  window.location.reload();
};
  const handleExport = (type) => {
    const expenses = getExpenses();
    if (type==="csv")    exportToCSV(expenses);
    if (type==="json")   exportToJSON(expenses);
    if (type==="report") generateTextReport(expenses, budget);
    setExportDone(type);
    setTimeout(() => setExportDone(""), 2000);
  };

  const Section = ({ title, children }) => (
    <div style={{ marginBottom:20 }}>
      <p style={{ fontSize:11, fontWeight:700, color:"#94A3B8", letterSpacing:"0.8px", textTransform:"uppercase", marginBottom:10 }}>{title}</p>
      <div style={{ background:"#fff", borderRadius:18, border:"1px solid #F1F5F9", overflow:"hidden", boxShadow:"0 2px 8px rgba(0,0,0,0.04)" }}>
        {children}
      </div>
    </div>
  );

  const Row = ({ emoji, label, right, onPress, last }) => (
    <div onClick={onPress} style={{
      display:"flex", alignItems:"center", gap:12, padding:"14px 16px",
      borderBottom: last?"none":"1px solid #F8FAFC",
      cursor: onPress?"pointer":"default", transition:"background 0.15s",
    }}
      onMouseEnter={e => onPress&&(e.currentTarget.style.background="#F8FAFC")}
      onMouseLeave={e => (e.currentTarget.style.background="#fff")}
    >
      <span style={{ fontSize:20, flexShrink:0 }}>{emoji}</span>
      <span style={{ flex:1, fontSize:13, fontWeight:500 }}>{label}</span>
      {right}
    </div>
  );

  return (
    <div style={{ minHeight:"100vh", background:"#F8FAFC" }}>
      <div className="animate-fadeInDown" style={{
        background:"linear-gradient(135deg,#4338CA,#6366F1)",
        padding:"52px 24px 36px", borderRadius:"0 0 28px 28px",
      }}>
        <h1 style={{ color:"#fff", fontSize:22, fontWeight:700, marginBottom:20 }}>Profile</h1>
        <div style={{ display:"flex", alignItems:"center", gap:16 }}>
          <div style={{ width:64, height:64, background:"rgba(255,255,255,0.25)", borderRadius:"50%", display:"flex", alignItems:"center", justifyContent:"center", color:"#fff", fontSize:28, fontWeight:700, border:"3px solid rgba(255,255,255,0.4)", flexShrink:0 }}>
            {user.name[0]}
          </div>
          <div>
            <p style={{ color:"#fff", fontSize:20, fontWeight:700 }}>{user.name}</p>
            <p style={{ color:"rgba(255,255,255,0.75)", fontSize:13, marginTop:2 }}>{user.email}</p>
            <div style={{ display:"inline-block", background:"rgba(255,255,255,0.2)", borderRadius:8, padding:"3px 10px", marginTop:8, color:"#fff", fontSize:11, fontWeight:600, border:"1px solid rgba(255,255,255,0.3)" }}>
              🎓 College Student
            </div>
          </div>
        </div>
      </div>

      <div style={{ padding:"20px 20px 0" }}>
        <div className="animate-fadeInUp" style={{ display:"flex", gap:12, marginBottom:24 }}>
          {[
            { label:"This Month", value:"₹5,550",  color:"#EF4444", bg:"#FEF2F2" },
            { label:"Budget",     value:`₹${budget.toLocaleString("en-IN")}`, color:"#4F46E5", bg:"#EEF2FF" },
            { label:"Savings",    value:"₹12,450", color:"#22C55E", bg:"#F0FDF4" },
          ].map(s => (
            <div key={s.label} style={{ flex:1, background:s.bg, borderRadius:14, padding:"12px 10px", textAlign:"center" }}>
              <p style={{ fontSize:14, fontWeight:700, color:s.color }}>{s.value}</p>
              <p style={{ fontSize:10, color:"#64748B", marginTop:3 }}>{s.label}</p>
            </div>
          ))}
        </div>

        <Section title="Export & Reports">
          <Row emoji="📊" label="Export as CSV"    right={exportDone==="csv"    ? <span style={{fontSize:12,color:"#22C55E",fontWeight:700}}>✓ Downloaded!</span> : <span style={{fontSize:12,color:"#94A3B8"}}>Spreadsheet ›</span>} onPress={() => handleExport("csv")} />
          <Row emoji="📋" label="Monthly Report"   right={exportDone==="report" ? <span style={{fontSize:12,color:"#22C55E",fontWeight:700}}>✓ Downloaded!</span> : <span style={{fontSize:12,color:"#94A3B8"}}>Text file ›</span>}    onPress={() => handleExport("report")} />
          <Row emoji="🗂️" label="Export as JSON"   right={exportDone==="json"   ? <span style={{fontSize:12,color:"#22C55E",fontWeight:700}}>✓ Downloaded!</span> : <span style={{fontSize:12,color:"#94A3B8"}}>Raw data ›</span>}     onPress={() => handleExport("json")} last />
        </Section>

        <Section title="Budget">
          <Row emoji="🎯" label="Monthly Budget"
            right={editingBudget ? (
              <div style={{ display:"flex", gap:6, alignItems:"center" }}>
                <input type="number" value={budgetInput} onChange={e=>setBudgetInput(e.target.value)}
                  style={{ width:90, padding:"5px 8px", border:"1.5px solid #4F46E5", borderRadius:8, fontSize:13, outline:"none", fontFamily:"'Poppins',sans-serif" }} autoFocus />
                <button onClick={() => { if(Number(budgetInput)>0) setBudget(Number(budgetInput)); setEditingBudget(false); }}
                  style={{ background:"#22C55E", border:"none", borderRadius:8, color:"#fff", padding:"5px 10px", fontSize:12, fontWeight:600 }}>Save</button>
              </div>
            ) : (
              <div style={{ display:"flex", gap:10, alignItems:"center" }}>
                <span style={{ fontSize:13, fontWeight:600, color:"#4F46E5" }}>₹{budget.toLocaleString("en-IN")}</span>
                <span style={{ color:"#94A3B8", fontSize:12 }}>›</span>
              </div>
            )}
            onPress={() => { setEditingBudget(true); setBudgetInput(String(budget)); }}
          />
          <Row emoji="💰" label="Currency" right={<span style={{fontSize:12,color:"#94A3B8"}}>INR (₹) ›</span>} last />
        </Section>

        <Section title="Preferences">
          // Find this row and update it:
          <Row emoji="🔔" label="Budget Alerts"
            right={
              <div onClick={async (e) => {
                e.stopPropagation();
                if (!notifications) {
                  const granted = await requestPermission();
                  setNotifications(granted);
                } else {
                  setNotifications(false);
                }
              }} style={{
                width:44, height:24,
                background: notifications ? "#4F46E5" : "#E2E8F0",
                borderRadius:12, position:"relative",
                transition:"background 0.2s", cursor:"pointer", flexShrink:0,
              }}>
                <div style={{ position:"absolute", top:2, left:notifications?22:2, width:20, height:20, background:"#fff", borderRadius:"50%", transition:"left 0.2s", boxShadow:"0 1px 4px rgba(0,0,0,0.2)" }} />
              </div>
            }
          />
          <Row emoji="🌙" label="Dark Mode"      right={<span style={{fontSize:11,color:"#94A3B8",fontStyle:"italic"}}>Coming soon</span>} />
          <Row emoji="🔒" label="Privacy Policy" right={<span style={{color:"#94A3B8",fontSize:12}}>›</span>} onPress={()=>{}} last />
        </Section>

        <Section title="About">
          <Row emoji="⭐" label="Rate the App" right={<span style={{color:"#94A3B8",fontSize:12}}>›</span>} onPress={()=>{}} />
          <Row emoji="ℹ️" label="Version"      right={<span style={{background:"#EEF2FF",color:"#4F46E5",fontSize:11,fontWeight:600,padding:"3px 8px",borderRadius:6}}>v1.0.0</span>} last />
        </Section>

        <button onClick={clearData} style={{ width:"100%", padding:"15px", background:"#F8FAFC", border:"1.5px solid #E2E8F0", borderRadius:16, color:"#64748B", fontSize:14, fontWeight:600, marginBottom:12, display:"flex", alignItems:"center", justifyContent:"center", gap:8 }}
          onMouseDown={e=>e.currentTarget.style.transform="scale(0.98)"} onMouseUp={e=>e.currentTarget.style.transform="scale(1)"}>
          🗑️ Reset All Data
        </button>

        <button onClick={onLogout} style={{ width:"100%", padding:"15px", background:"#FEF2F2", border:"1.5px solid #FECACA", borderRadius:16, color:"#EF4444", fontSize:14, fontWeight:700, marginBottom:32, display:"flex", alignItems:"center", justifyContent:"center", gap:8 }}
          onMouseDown={e=>e.currentTarget.style.transform="scale(0.98)"} onMouseUp={e=>e.currentTarget.style.transform="scale(1)"}>
          🚪 Logout
        </button>
      </div>
    </div>
  );
}
